server:
  port: 8090
  servlet:
    session:
      timeout: -1s
  maxHttpHeaderSize: 10240000
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.93.1:3306/report?userUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=UCT&rewirteBatchedStatements=true&allowMultiQueries=true
#    url: jdbc:mysql://localhost:3306/fisher?useSSL=false
#    url: jdbc:mysql://localhost:3306/report?useSSL=false
    username: root
    password: PassWord@1991
    tomcat:
      initSQL: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
  profiles:
    active: dev

application:
  enableSwitchForService1: true
  service1Url: http://abc-dev.service.com/somethingelse
  service1Timeout: 250

  security:
    basic:
      enabled: false
    user:
      name: user-name
      password: user-password
  management:
    security:
      enabled: false


somedataservice:
  url: http://abc.service.com/something
